### ISSUE TITLE
question.. html5?

### ISSUE THREAD

**Issue by Cryptosports** [wezrule/UE4NanoPlugin#14]
Hi, 
The last patch said something about getting it built in html5.. the project is in 4.25 which doesn't have html5 support, or am I missing a 4.25 plugin? I havent seen it in the package menus for a few versions now, so even if the nano plugin compiled in 4.23 , the demo scene wont load because the scenes arent backwards compatible.  Great work btw. Just kind of discovered nano and am interested in puting it into my games in ue4 and u3d. Cheers. I guess I never really asked anything lol you can close this.

**Comment by wezrule** [comment]
HTML support for UE4 is no longer officially supported, there is a community run HTML branch which is still on 4.24. It doesn't support `libwebsocket` so there are some issues there, which is why it's not mentioned as a supported version on main page yet. It's non-trivial to update, but was attempted, and until it is made easier will probably not be ported.
